version: '3.8'

services:
  rasa:
    image: python:3.8-slim
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - rasa-sdk
    command: >
      sh -c "pip install rasa"

  rasa-sdk:
    image: python:3.8-slim
    ports:
      - "5055:5055"
    volumes:
      - ./app/actions:/app/actions
    working_dir: /app/actions
    command: >
      sh -c "pip install rasa-sdk rasa && rasa run actions"
